version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: postgres
    container_name: neoway_data
    restart: always
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=neoway
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data      
